# Generated by Django 3.1.7 on 2021-04-15 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_auto_20210414_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='has_disliked',
            field=models.ManyToManyField(blank=True, related_name='has_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='has_liked',
            field=models.ManyToManyField(blank=True, related_name='has_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
