# Generated by Django 3.1.7 on 2021-04-17 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('net', '0003_auto_20210415_1954'),
        ('notification', '0002_auto_20210416_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='subnet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notified_subnet', to='net.net'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='post_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notified_post', to='posts.post'),
        ),
    ]
