# Generated by Django 3.1.7 on 2021-04-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20210417_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Post', 'Post'), ('Subnet', 'Subnet')], default='Post', max_length=20),
        ),
    ]
