# Generated by Django 3.1.7 on 2021-04-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20210417_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Post', 'Post'), ('Subnet', 'Subnet'), ('Message', 'Message')], default='Post', max_length=20),
        ),
    ]
