# Generated by Django 3.1.7 on 2021-04-06 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0002_net_moderators'),
        ('net_user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='netuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netuser',
            name='followers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='netuser',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='netuser',
            name='subs',
            field=models.ManyToManyField(blank=True, related_name='subs', to='net.Net'),
        ),
        migrations.AlterField(
            model_name='netuser',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
