# Generated by Django 3.1.7 on 2021-04-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_user_app', '0002_auto_20210406_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='netuser',
            name='site_theme',
            field=models.CharField(blank=True, choices=[('Light', 'Light'), ('Dark', 'Dark')], default='Light', max_length=10, null=True),
        ),
    ]
