# Generated by Django 3.1.7 on 2021-04-13 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_user_app', '0002_netuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netuser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='Users_Followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
