# Generated by Django 3.1.7 on 2021-04-06 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('net', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='net',
            name='moderators',
            field=models.ManyToManyField(related_name='moderators', to=settings.AUTH_USER_MODEL),
        ),
    ]
