# Generated by Django 3.1.7 on 2021-04-06 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0002_net_moderators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='net',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
