# Generated by Django 3.1.7 on 2021-04-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0002_net_moderators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='net',
            name='subscribers',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
